"use client";
import {EditorialImage as Image} from "@/components/media/EditorialImage";import Link from "next/link";import {useMemo,useState} from "react";import {AnimatePresence,motion} from "framer-motion";import {barbers,looks,services} from "@/data/site";import {media} from "@/data/media";import {RevealLines,RevealText} from "@/components/motion/RevealText";import {useBooking} from "@/components/providers/BookingProvider";import {usePublicData} from "@/components/providers/PublicDataProvider";
export function BarbersExperience(){const booking=useBooking();const {barbers}=usePublicData();const [active,setActive]=useState(0);const [skill,setSkill]=useState('TEXTURE');const matches=useMemo(()=>barbers.filter(b=>b.specialties.some(s=>s.includes(skill)||skill.includes(s.split(' ')[0]))),[skill,barbers]);return <main className="barbers-v2">
<section className="barber-opening"><div className="barber-opening-copy"><span>01 / THE BARBERS</span><h1><RevealLines lines={['THE HAND']}/><em><RevealLines lines={['MATTERS.']}/></em></h1><p>Different eyes. Different strengths. Same house standard. Choose the person whose work makes sense for what you need.</p></div><div className="portrait-slices">{barbers.map((b,i)=><motion.button key={b._id} animate={{flex:active===i?2.4:1}} onMouseEnter={()=>setActive(i)} onFocus={()=>setActive(i)} onClick={()=>booking.setBarber(b)} transition={{duration:.5,ease:[.16,1,.3,1]}}><Image src={b.portrait||media.portraits[i]} alt={b.name} fill/><div><span>CHAIR {b.chairNumber}</span><b>{b.name}</b><small>{b.specialties.join(' / ')}</small></div></motion.button>)}</div></section>
<section className="barber-matcher"><div><span>02 / START WITH THE WORK</span><h2>WHAT DO YOU<br/><em>CARE ABOUT?</em></h2></div><div className="skill-wheel">{['TEXTURE','FADE','BEARD','SCISSOR','CLASSIC','LONG HAIR'].map(x=><button className={skill===x?'active':''} onClick={()=>setSkill(x)} key={x}>{x}<i></i></button>)}</div><div className="matcher-result"><small>BEST START</small><AnimatePresence mode="wait"><motion.div key={matches[0]?.slug||'all'} initial={{opacity:0,y:20}} animate={{opacity:1,y:0}} exit={{opacity:0,y:-20}}><b>{matches[0]?.name||'ANY CHAIR'}</b><p>{matches[0]?.bio||'Every barber can start the conversation.'}</p>{matches[0]&&<Link href={`/barbers/${matches[0].slug}`}>OPEN PROFILE </Link>}</motion.div></AnimatePresence></div></section>
<section className="barber-chair-map"><div className="map-title"><span>03 / HOUSE MAP</span><h2>WHERE THEY<br/><em>WORK.</em></h2><p>The same four chairs you see on the home page, now mapped to the people behind them.</p></div><div className="barber-floor"><span className="floor-entry">ENTRY / </span>{barbers.map((b,i)=><motion.div key={b._id} className={`bf-${i+1}`} whileHover={{scale:1.08}}><i/><span>{b.chairNumber}</span><b>{b.name.split(' ')[0]}</b><small>{b.specialties[0]}</small></motion.div>)}</div></section>
<section className="portrait-darkroom"><span>04 / PORTRAIT STUDIES</span><div>{barbers.map((b,i)=><motion.figure key={b._id} whileHover="hover"><motion.div variants={{hover:{filter:'grayscale(0%)',scale:1.03}}} initial={{filter:'grayscale(100%)'}}><Image src={b.portrait||media.portraits[i]} alt={b.name} fill/></motion.div><figcaption><span>0{i+1}</span><b>{b.name}</b><small>CHAIR {b.chairNumber}</small></figcaption></motion.figure>)}</div></section>
<section className="philosophy-lines"><span>05 / FOUR PHILOSOPHIES</span>{[['JACK','A FADE SHOULD STILL MAKE SENSE ON DAY TEN.'],['MASON','LONGER HAIR NEEDS WEIGHT IN THE RIGHT PLACE, NOT LESS HAIR EVERYWHERE.'],['ELLIOT','DETAIL SHOULD FEEL CLEAN, NEVER OVERDRAWN.'],['NOAH','THE BEST TEXTURE LOOKS LIKE YOUR HAIR DECIDED TO BEHAVE.']].map(([n,q],i)=><motion.article key={n} whileInView={{x:0,opacity:1}} initial={{x:i%2?-80:80,opacity:0}} viewport={{once:true}}><b>{n}</b><h2>“{q}”</h2><span>0{i+1}</span></motion.article>)}</section>
<section className="signature-work"><div className="section-index inverse"><span>06</span><b>SIGNATURE WORK</b><small>WHO MADE WHAT</small></div>{looks.slice(0,4).map((l,i)=><Link href={`/barbers/${l.barber.slug}`} className={`sig-${i+1}`} key={l.id}><Image src={l.image} alt={l.title} fill/><span>{l.barber.name}</span><b>{l.title}</b><i>OPEN PROFILE </i></Link>)}</section>
<section className="barber-availability"><div><span>07 / AVAILABILITY</span><h2>WHO CAN TAKE<br/><em>YOU NEXT?</em></h2></div><div>{barbers.map((b,i)=><button key={b._id} onClick={()=>booking.setBarber(b)}><span>{['17:30','18:00','18:15','18:45'][i%4]}</span><b>{b.name}</b><small>CHAIR {b.chairNumber}</small><i>SELECT </i></button>)}</div></section>
<section className="interview-tape"><div className="tape-image"><Image src={media.tools} alt="Barber interview" fill/><span>08 / HOUSE TAPE</span></div><div className="tape-copy"><small>Q / WHAT MAKES A GOOD CONSULTATION?</small><h2>“DON'T TELL ME THE HAIRCUT NAME.<br/><em>TELL ME WHAT'S ANNOYING YOU.”</em></h2><p>JACK / CHAIR 01</p><Link href="/barbers/jack">READ THE FULL PROFILE </Link></div></section>
<section className="behind-chair-video"><Image src={media.house} alt="Behind the chair" fill/><div/><span>09 / BEHIND THE CHAIR / 00:41</span><h2>WATCH THE<br/><em>PACE.</em></h2><div className="film-meta">HOUSE FILM / 00:41</div></section>
<section className="barber-compare"><span>10 / COMPARE</span><h2>DIFFERENT HANDS.<br/><em>CLEAR LANES.</em></h2><div className="compare-grid"><div className="compare-head"><span>BARBER</span><span>STRONGEST IN</span><span>PACE</span><span>NEXT</span></div>{barbers.map((b,i)=><Link href={`/barbers/${b.slug}`} key={b._id}><b>{b.name}</b><span>{b.specialties.slice(0,2).join(' / ')}</span><span>{['PRECISE','CALM','STRUCTURED','LOOSE'][i%4]}</span><strong>{['17:30','18:00','18:15','18:45'][i%4]} </strong></Link>)}</div></section>
<section className="client-pairing"><div><span>11 / CLIENT PAIRING</span><h2>THE RIGHT BARBER<br/><em>SHOULD REDUCE<br/>DECISIONS.</em></h2><p>Once someone understands how you wear your hair, rebooking should feel almost automatic.</p></div><div className="pairing-cards">{barbers.map((b,i)=><motion.article key={b._id} whileHover={{rotate:i%2?-2:2,y:-8}}><span>BEST FOR</span><b>{b.specialties[0]} / {b.specialties[1]}</b><small>CHAIR {b.chairNumber}</small><Link href={`/barbers/${b.slug}`}>{b.name} </Link></motion.article>)}</div></section>
<section className="barber-final"><span>12 / TAKE A CHAIR</span><h2><RevealText>KNOW WHO YOU WANT?</RevealText><br/><em><RevealText>MAKE IT THEIRS.</RevealText></em></h2><Link href="/booking">CHOOSE YOUR BARBER </Link></section>
</main>}
