"use client";
import {EditorialImage as Image} from "@/components/media/EditorialImage";import Link from "next/link";import {motion,useScroll,useTransform} from "framer-motion";import {useRef,useState} from "react";import {barbers,looks,services} from "@/data/site";import {media} from "@/data/media";import {RevealLines,RevealText} from "@/components/motion/RevealText";import {ScrollWords} from "@/components/motion/ScrollWords";import {useBooking} from "@/components/providers/BookingProvider";import {usePublicData} from "@/components/providers/PublicDataProvider";import {useDesktopMotion} from "@/components/motion/useMotionMode";
export function BarberProfileExperience({slug}:{slug:string}){const desktop=useDesktopMotion();const {barbers,services}=usePublicData();const barber=barbers.find(b=>b.slug===slug)||barbers[0];const index=barbers.indexOf(barber);const booking=useBooking();const [clientActive,setClientActive]=useState(0);const hero=useRef<HTMLElement>(null);const{scrollYProgress}=useScroll({target:hero,offset:['start start','end start']});const imgY=useTransform(scrollYProgress,[0,1],[0,150]);const nameX=useTransform(scrollYProgress,[0,1],[0,-100]);const work=looks.filter((_,i)=>i%4===index%4).concat(looks.slice(0,3));return <main className="profile-v2">
<section ref={hero} className="profile-hero"><motion.div className="profile-photo" style={desktop?{y:imgY}:undefined}><Image src={barber.portrait||media.portraits[index]} alt={barber.name} fill priority/></motion.div><div className="profile-number">CHAIR / {barber.chairNumber}</div><motion.h1 style={desktop?{x:nameX}:undefined}><RevealLines lines={[barber.name.split(' ')[0]]}/><em><RevealLines lines={[barber.name.split(' ')[1]]}/></em></motion.h1><div className="profile-skills">{barber.specialties.map(s=><span key={s}>{s}</span>)}</div><button onClick={()=>booking.setBarber(barber)}>BOOK WITH {barber.name.split(' ')[0]} </button></section>
<section className="profile-intro"><span>02 / PROFILE</span><ScrollWords text={barber.bio+" The aim is not to make a haircut look impressive for five minutes in a mirror. The aim is to make the shape easier to live with for the weeks after."}/><aside><small>HOUSE SINCE</small><b>{2019+index}</b><small>CHAIR</small><b>{barber.chairNumber}</b></aside></section>
<section className="profile-signature"><div><span>03 / SIGNATURE</span><h2>WHAT {barber.name.split(' ')[0]}<br/><em>SEES FIRST.</em></h2></div>{barber.specialties.map((s,i)=><article key={s}><span>0{i+1}</span><b>{s}</b><p>{['The transition and how it survives growth.','Where weight should stay instead of disappear.','The line between clean detail and overworking it.'][i%3]}</p></article>)}</section>
<section className="profile-work"><div className="section-index inverse"><span>04</span><b>SELECTED WORK</b><small>{barber.name}</small></div>{work.slice(0,4).map((l,i)=><figure className={`pw-${i+1}`} key={`${l.id}-${i}`}><Image src={l.image} alt={l.title} fill/><figcaption><span>{l.category}</span><b>{l.title}</b></figcaption></figure>)}</section>
<section className="profile-interview"><span>05 / SHORT INTERVIEW</span><div><small>WHAT SHOULD A CLIENT BRING?</small><h2>“A REFERENCE HELPS.<br/><em>BUT THE PROBLEM<br/>HELPS MORE.”</em></h2></div><div><small>WHAT DO YOU NOTICE FIRST?</small><h3>{barber.specialties[0]}. THEN HOW THE HAIR WANTS TO MOVE WITHOUT PRODUCT.</h3></div></section>
<section className="profile-tool"><div className="tool-image"><Image src={media.tools} alt="Barber tools" fill/></div><div><span>06 / ONE TOOL</span><h2>THE COMB<br/><em>BEFORE THE<br/>CLIPPER.</em></h2><p>The first useful thing is not cutting. It is seeing where the hair changes direction, collapses, or holds too much weight.</p></div></section>
<section className="profile-process"><span>07 / PROCESS</span>{['LISTEN','MAP','CUT','CHECK','FINISH'].map((x,i)=><motion.div key={x} initial={{scaleX:.2}} whileInView={{scaleX:1}} viewport={{once:true}} transition={{duration:.6,delay:i*.1}}><span>0{i+1}</span><b>{x}</b><small>{['What is bothering you?','Where should weight live?','Build the silhouette.','Cross-check in another direction.','Show you how it behaves.'][i]}</small></motion.div>)}</section>
<section className="profile-clients"><div><span>08 / CLIENT WORK</span><h2>REAL HAIR.<br/><em>DIFFERENT DAYS.</em></h2></div><div className="client-strip">{work.slice(0,5).map((l,i)=><motion.figure key={`${l.id}-c${i}`} animate={desktop?{flex:clientActive===i?1.8:1}:undefined} onMouseEnter={()=>setClientActive(i)} onFocus={()=>setClientActive(i)} tabIndex={0} transition={{duration:.45,ease:[.16,1,.3,1]}}><Image src={l.image} alt={l.title} fill/><figcaption>{l.title}</figcaption></motion.figure>)}</div></section>
<section className="profile-film"><Image src={media.house} alt="Barber behind chair" fill/><div/><span>09 / 00:38 / BEHIND CHAIR {barber.chairNumber}</span><h2>{barber.name.split(' ')[0]}<br/><em>AT WORK.</em></h2><div className="film-meta">BEHIND THE CHAIR / 00:38</div></section>
<section className="profile-quote"><span>10 / CLIENT NOTE</span><h2>“I DON'T HAVE TO<br/>EXPLAIN IT AGAIN.<br/><em>THAT'S THE POINT.”</em></h2><p>RETURNING CLIENT / CHAIR {barber.chairNumber}</p></section>
<section className="profile-availability"><div><span>11 / NEXT WITH {barber.name.split(' ')[0]}</span><h2>TAKE THE<br/><em>NEXT OPENING.</em></h2></div><div>{['17:30','18:15','19:00','TOMORROW 10:15'].map((t,i)=><button key={t} onClick={()=>{booking.setBarber(barber);booking.setService(services[i%services.length]);if(!t.includes('TOMORROW'))booking.setTime(t)}}><span>{t}</span><b>{services[i%services.length].name}</b><small>{services[i%services.length].duration} MIN</small><i>SELECT </i></button>)}</div></section>
<section className="profile-rebook"><span>12 / CONTINUITY</span><h2>SAME CHAIR.<br/><em>LESS EXPLAINING.</em></h2><p>Once {barber.name.split(' ')[0]} knows the shape, your account can hold the last service and make the next booking faster.</p><Link href="/account">OPEN CLIENT ACCOUNT </Link></section>
<section className="profile-final"><span>13 / BOOK WITH {barber.name.split(' ')[0]}</span><h2><RevealText>{`CHAIR ${barber.chairNumber} IS OPEN.`}</RevealText></h2><Link href="/booking" onClick={()=>booking.setBarber(barber)}>BOOK WITH {barber.name.split(' ')[0]} </Link></section>
</main>}
