"use client";
import {EditorialImage as Image} from "@/components/media/EditorialImage";import Link from "next/link";import {useRef} from "react";import {motion,useScroll,useTransform} from "framer-motion";import {media} from "@/data/media";import {barbers} from "@/data/site";import {RevealLines,RevealText} from "@/components/motion/RevealText";import {ParallaxMedia} from "@/components/motion/ParallaxMedia";import {ScrollWords} from "@/components/motion/ScrollWords";import {useDesktopMotion} from "@/components/motion/useMotionMode";
export function HouseExperience(){const desktop=useDesktopMotion();const entry=useRef<HTMLElement>(null);const{scrollYProgress}=useScroll({target:entry,offset:['start start','end end']});const door=useTransform(scrollYProgress,[0,.7,1],["inset(0 0 0 0)","inset(10% 28% 10% 28%)","inset(0 0 0 0)"]);return <main className="house-v2">
<section className="house-hero"><ParallaxMedia src={media.exterior} alt="The Chair exterior" speed={10}/><div className="house-hero-shade"/><span>01 / THE HOUSE</span><h1><RevealLines lines={['A ROOM']}/><em><RevealLines lines={['BUILT FOR','TIME.']}/></em></h1><p>Part workshop. Part ritual. Four chairs, a deliberately small team and enough space around an appointment to keep it from feeling transactional.</p></section>
<section ref={entry} className="house-entry"><div className="entry-pin"><motion.div className="entry-image" style={desktop?{clipPath:door}:undefined}><Image src={media.house} alt="Entering The Chair" fill/></motion.div><div className="entry-steps"><span>02 / ENTRY SEQUENCE</span><h2>STREET / </h2><h2>DOOR / </h2><h2><em>CHAIR.</em></h2></div></div></section>
<section className="house-manifesto"><span>03 / HOUSE RULE</span><ScrollWords text="A premium room is not one that asks you to admire it. It is one that quietly removes friction: where to sit, what happens next, how long you have, who is looking after you, and why nothing feels rushed."/></section>
<section className="founder-story"><div className="founder-portrait"><Image src={media.portraits[1]} alt="The Chair founder" fill/></div><div><span>04 / FOUNDER NOTE</span><h2>“THE IDEA WASN'T<br/>TO BUILD A BIGGER<br/><em>BARBERSHOP.”</em></h2><p>It was to build a better appointment: fewer chairs, stronger work, clearer booking and a space where the pace could stay human.</p><b>M. REED / FOUNDER</b></div></section>
<section className="house-years"><span>05 / THE YEARS</span>{[['2018','ONE ROOM','The first chair opens.'],['2020','THE HOUSE','A second room and a slower format.'],['2023','FOUR CHAIRS','The team settles at four.'],['2026','THE SYSTEM','Booking, membership and client continuity become one product.']].map(([y,t,c],i)=><motion.article key={y} initial={{x:i%2?-100:100,opacity:0}} whileInView={{x:0,opacity:1}} viewport={{once:true}}><span>{y}</span><b>{t}</b><p>{c}</p></motion.article>)}</section>
<section className="architecture-plan"><div><span>06 / ARCHITECTURE</span><h2>THE ROOM<br/><em>IS A WORKFLOW.</em></h2><p>Entry, waiting, wash, four working stations and a quieter back edge. The plan keeps client movement simple and gives every chair breathing room.</p></div><div className="arch-drawing"><svg viewBox="0 0 800 520"><motion.path d="M80 450V70H700V450H80ZM80 160H700M260 70V450M470 70V450M700 240H760V450H700" initial={{pathLength:0}} whileInView={{pathLength:1}} viewport={{once:true}} transition={{duration:2}}/><circle cx="175" cy="290" r="40"/><circle cx="365" cy="290" r="40"/><circle cx="570" cy="290" r="40"/><circle cx="650" cy="380" r="40"/></svg><span>CHAIR 01</span><span>CHAIR 02</span><span>CHAIR 03</span><span>CHAIR 04</span></div></section>
<section className="materials"><div className="section-index inverse"><span>07</span><b>MATERIALS / NOT DECOR</b><small>WHAT THE ROOM IS MADE OF</small></div>{[[media.tools,'STEEL','TOOLS THAT AGE THROUGH USE'],[media.house,'OAK','WARMTH WITHOUT SOFTNESS'],[media.towel,'CLOTH','THE QUIET LAYER'],[media.chair,'LEATHER','THE OBJECT EVERYTHING ORBITS']].map(([img,t,c],i)=><figure key={String(t)} className={`mat-${i+1}`}><Image src={String(img)} alt={String(t)} fill/><figcaption><b>{t}</b><span>{c}</span></figcaption></figure>)}</section>
<section className="tools-wall"><div><span>08 / TOOLS</span><h2>OBJECTS WITH<br/><em>A JOB.</em></h2></div>{['CLIPPER','SHEAR','COMB','RAZOR','BRUSH','DRYER'].map((t,i)=><motion.div key={t} whileHover={{x:18}}><span>0{i+1}</span><b>{t}</b><small>{['REMOVE','SHAPE','READ','EDGE','CLEAR','FINISH'][i]}</small></motion.div>)}</section>
<section className="ritual"><div className="ritual-image"><Image src={media.detail} alt="Barber ritual" fill/></div><div><span>09 / THE RITUAL</span><h2>THE SAME<br/><em>ORDER.</em><br/>DIFFERENT CUT.</h2><ol><li>ARRIVE</li><li>CONSULT</li><li>PREP</li><li>CUT</li><li>DETAIL</li><li>FINISH</li></ol></div></section>
<section className="house-team"><span>10 / THE TEAM</span><h2>FOUR CHAIRS.<br/><em>NO BENCH.</em></h2><div>{barbers.map((b,i)=><Link href={`/barbers/${b.slug}`} key={b._id}><div><Image src={b.portrait||media.portraits[i]} alt={b.name} fill/></div><span>{b.chairNumber}</span><b>{b.name}</b><small>{b.specialties.join(' / ')}</small></Link>)}</div></section>
<section className="day-sequence"><span>11 / A DAY IN THE HOUSE</span>{[['08:35','LIGHTS'],['09:00','FIRST CHAIR'],['12:30','RESET'],['15:00','AFTERNOON'],['18:15','LAST RUN'],['20:06','HOUSE QUIET']].map(([t,n],i)=><motion.article key={t} whileInView={{flexGrow:i===3?2:1}}><span>{t}</span><b>{n}</b></motion.article>)}</section>
<section className="house-philosophy"><span>12 / HOUSE PHILOSOPHY</span><h2>GOOD DESIGN<br/>SHOULD MAKE THE<br/><em>APPOINTMENT FEEL<br/>OBVIOUS.</em></h2><p>The brand, the room and the booking system all have the same job: remove uncertainty without removing personality.</p></section>
<section className="house-final"><span>13 / COME IN</span><h2><RevealText>SEE THE ROOM.</RevealText><br/><em><RevealText>TAKE A CHAIR.</RevealText></em></h2><div><Link href="/visit">FIND THE HOUSE </Link><Link href="/booking">BOOK A CHAIR </Link></div></section>
</main>}
