"use client";
import {EditorialImage as Image} from "@/components/media/EditorialImage";import Link from "next/link";import {AnimatePresence,motion} from "framer-motion";import {useState} from "react";import {journal,barbers} from "@/data/site";import {media} from "@/data/media";import {RevealLines,RevealText} from "@/components/motion/RevealText";import {usePublicData} from "@/components/providers/PublicDataProvider";
export function JournalExperience(){const {journal,barbers}=usePublicData();const [reader,setReader]=useState<any>(null);const [index,setIndex]=useState('ALL');const [joined,setJoined]=useState(false);const feature=journal[0];const leadBarber=barbers[0];if(!feature||!leadBarber)return <main className="journal-v2 journal-empty"><span>JOURNAL / LOADING</span><h1>OPENING THE ISSUE.</h1></main>;return <main className="journal-v2">
<section className="journal-hero"><div><span>01 / JOURNAL</span><h1><RevealLines lines={['NOTES FROM']}/><em><RevealLines lines={['BEHIND','THE CHAIR.']}/></em></h1></div><p>Useful answers, observations from the floor, interviews and visual studies. Less content machine. More independent house publication.</p><div className="issue-mark">ISSUE<br/><b>06</b><small>AUG / 26</small></div></section>
<section className="journal-feature-v2"><div className="jf-image"><Image src={feature.cover||media.detail} alt={feature.title} fill/></div><div><span>02 / FEATURE / 06 MIN</span><h2>{feature.title}</h2><p>{feature.excerpt}</p><button type="button" onClick={()=>setReader(feature)}>READ THE FEATURE</button></div></section>
<section className="journal-ticker"><motion.div animate={{x:['0%','-50%']}} transition={{duration:28,repeat:Infinity,ease:'linear'}}>FIELD NOTES / BARBER ANSWERS / GUIDES / HOUSE STORIES / PHOTO ESSAYS / FIELD NOTES / BARBER ANSWERS / GUIDES / HOUSE STORIES / PHOTO ESSAYS / </motion.div></section>
<section className="journal-shortreads"><span>04 / SHORT READS</span>{journal.slice(1).filter((j:any)=>index==='ALL'||String(j.type||'').toUpperCase().includes(index)).map((j,i)=><motion.article key={j.slug} whileHover={{x:12}} onClick={()=>setReader(j)} tabIndex={0} onKeyDown={e=>{if(e.key==='Enter')setReader(j)}}><span>0{i+1}</span><small>{j.type} / 03 MIN</small><h2>{j.title}</h2><p>{j.excerpt}</p><i></i></motion.article>)}</section>
<section className="journal-interview"><div><Image src={leadBarber.portrait||media.portraits[0]} alt={`${leadBarber.name} interview`} fill/></div><article><span>05 / INTERVIEW / JACK HARPER</span><small>Q / WHAT DO PEOPLE ASK FOR THAT THEY DON'T ACTUALLY MEAN?</small><h2>“SHORTER<br/><em>EVERYWHERE.”</em></h2><p>Usually they mean the shape feels too heavy in one area. Taking length off everywhere solves the sentence, not the problem.</p><Link href="/barbers/jack">MEET JACK </Link></article></section>
<section className="barber-answer"><span>06 / BARBER ANSWER</span><h2>HOW OFTEN<br/>SHOULD I<br/><em>ACTUALLY COME?</em></h2><div><p>Short fade</p><b>2–3 WEEKS</b></div><div><p>Classic short</p><b>3–5 WEEKS</b></div><div><p>Long / scissor</p><b>5–8 WEEKS</b></div><Link href="/membership">BUILD YOUR RHYTHM </Link></section>
<section className="journal-guide"><div><span>07 / GUIDE</span><h2>THE REFERENCE<br/><em>PHOTO TEST.</em></h2><p>If you bring a haircut photo, identify these four things before the appointment.</p></div><ol><li><b>01</b>WHAT DO YOU LIKE ABOUT THE SHAPE?</li><li><b>02</b>HOW CLEAN DO YOU WANT THE EDGE?</li><li><b>03</b>DO YOU LIKE THE TEXTURE OR JUST THE PERSON?</li><li><b>04</b>WHAT PART WOULD NOT WORK IN YOUR ROUTINE?</li></ol></section>
<section className="photo-story"><span>08 / PHOTO STORY / 14:32</span><div>{[media.tools,media.towel,media.chair,media.detail,media.house].map((x,i)=><figure key={x}><Image src={x} alt="Afternoon in The Chair" fill/><figcaption>14:{32+i*4} / FRAME 0{i+1}</figcaption></figure>)}</div><h2>AN AFTERNOON<br/><em>BETWEEN CHAIRS.</em></h2></section>
<section className="journal-index"><span>09 / INDEX</span><button className={index==='ALL'?'active':''} onClick={()=>setIndex('ALL')}><span>00</span><b>ALL</b><small>{journal.length} STORIES</small><i/></button>{['CUTS','BEARDS','GROWTH','PRODUCT','HOUSE','PEOPLE'].map((x,i)=><button className={index===x?'active':''} onClick={()=>setIndex(x)} key={x}><span>0{i+1}</span><b>{x}</b><small>{[8,4,6,3,9,7][i]} STORIES</small><i/></button>)}</section>
<section className="journal-quote"><span>10 / MARGIN NOTE</span><h2>“YOUR HAIR DOESN'T<br/>KNOW THE NAME OF<br/><em>THE HAIRCUT.”</em></h2><p>HOUSE NOTE / ISSUE 06</p></section>
<section className="journal-subscribe"><div><span>11 / HOUSE LETTER</span><h2>ONE EMAIL.<br/><em>WHEN WE HAVE<br/>SOMETHING USEFUL.</em></h2></div><form onSubmit={e=>{e.preventDefault();setJoined(true)}}><input type="email" required placeholder="YOUR EMAIL"/><button type="submit">{joined?'YOU ARE ON THE LIST':'JOIN THE LIST'}</button></form></section>
<section className="journal-final"><span>12 / NEXT ISSUE</span><h2><RevealText>READ LESS.</RevealText><br/><em><RevealText>NOTICE MORE.</RevealText></em></h2><Link href="/booking">OR JUST BOOK A CHAIR </Link></section>
<AnimatePresence>{reader&&<motion.div className="journal-reader" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} role="dialog" aria-modal="true"><motion.article initial={{y:50}} animate={{y:0}} exit={{y:30}}><button className="reader-close" onClick={()=>setReader(null)} aria-label="Close article">CLOSE</button><span>THE CHAIR / JOURNAL</span><h2>{reader.title}</h2><p className="reader-lead">{reader.excerpt}</p><div className="reader-image"><Image src={reader.cover||media.detail} alt={reader.title} fill/></div><p>{reader.body||'A considered note from behind the chair. The full editorial body can be managed from the journal section in the control room.'}</p></motion.article></motion.div>}</AnimatePresence></main>}
