"use client";
import {EditorialImage as Image} from "@/components/media/EditorialImage";import Link from "next/link";import {AnimatePresence,motion} from "framer-motion";import {useMemo,useState} from "react";import {looks} from "@/data/site";import {RevealLines,RevealText} from "@/components/motion/RevealText";import {useBooking} from "@/components/providers/BookingProvider";import {usePublicData} from "@/components/providers/PublicDataProvider";
export function LookbookExperience(){const {lookbook:looks}=usePublicData();const [filter,setFilter]=useState('ALL');const [active,setActive]=useState<string|null>(null);const booking=useBooking();const cats=['ALL','FADES','TEXTURE','CLASSIC','LONG','BEARDS'];const items=useMemo(()=>filter==='ALL'?looks:looks.filter(x=>x.category===filter),[filter,looks]);const selected=looks.find(x=>x.id===active);return <main className="lookbook-v2">
<section className="look-hero"><div><span>01 / WORK</span><h1><RevealLines lines={['DON’T COPY']}/><em><RevealLines lines={['THE PHOTO.']}/></em></h1><p>Use it to start the conversation. Shape, weight, edge, texture — your barber translates the reference to the person in the chair.</p></div><div className="chaos-collage">{looks.slice(0,5).map((l,i)=><motion.figure key={l.id} className={`chaos-${i+1}`} initial={{rotate:[-9,6,-4,8,-6][i],x:[-30,20,60,-20,10][i],y:[30,-15,20,50,-30][i]}} whileInView={{rotate:0,x:0,y:0}} viewport={{once:true}} transition={{duration:1,ease:[.16,1,.3,1]}}><Image src={l.image} alt={l.title} fill/></motion.figure>)}</div></section>
<section className="look-filter"><span>02 / FILTER THE WALL</span><div>{cats.map(c=><button key={c} className={filter===c?'active':''} onClick={()=>setFilter(c)}>{c}<i>{looks.filter(x=>c==='ALL'||x.category===c).length}</i></button>)}</div></section>
<section className="look-grid"><AnimatePresence mode="popLayout">{items.map((l,i)=><motion.button layout key={l.id} className={`look-item li-${(i%6)+1}`} initial={{opacity:0,scale:.9}} animate={{opacity:1,scale:1}} exit={{opacity:0,scale:.9}} onClick={()=>setActive(l.id)} whileHover={{y:-6}} data-cursor="VIEW"><Image src={l.image} alt={l.title} fill/><span>{l.category}</span><b>{l.title}</b><small>BY {l.barber.name}</small></motion.button>)}</AnimatePresence></section>
<section className="look-reference"><span>04 / HOW TO USE A REFERENCE</span><h2>SHOW THE<br/><em>PART YOU LIKE.</em></h2><div>{[['01','SHAPE','The overall silhouette.'],['02','WEIGHT','Where it feels heavy or light.'],['03','EDGE','Soft, clean, natural or sharp.'],['04','TEXTURE','Polished, loose, separated, matte.']].map(([n,t,c])=><article key={n}><span>{n}</span><b>{t}</b><p>{c}</p></article>)}</div></section>
<section className="look-detail-study"><div className="detail-study-image"><Image src={looks[0].image} alt="Taper detail" fill/><span>A / EDGE</span><span>B / WEIGHT</span><span>C / TEXTURE</span></div><div><span>05 / ONE LOOK, THREE DECISIONS</span><h2>LOW TAPER.<br/><em>TEXTURED TOP.</em></h2><p>The useful part of a reference is not the haircut name. It is the relationship between edge, weight and texture.</p></div></section>
<section className="look-barber-index"><span>06 / WHO MADE IT</span>{looks.slice(0,4).map((l,i)=><Link href={`/barbers/${l.barber.slug}`} key={l.id}><span>0{i+1}</span><b>{l.barber.name}</b><small>{l.title}</small><i>PROFILE </i></Link>)}</section>
<section className="look-before-after"><div><span>07 / TRANSFORMATION PAIR</span><h2>SAME PERSON.<br/><em>BETTER SHAPE.</em></h2></div><div className="ba-images"><figure><Image src={looks[4].image} alt="Before" fill/><span>BEFORE / WEIGHT DRIFT</span></figure><figure><Image src={looks[2].image} alt="After" fill/><span>AFTER / SHAPE RESTORED</span></figure></div></section>
<section className="look-motion-strip"><span>08 / TEXTURE IN MOTION</span><div>{looks.concat(looks).slice(0,10).map((l,i)=><motion.figure key={`${l.id}-${i}`} whileHover={{scale:1.06}}><Image src={l.image} alt={l.title} fill/></motion.figure>)}</div></section>
<section className="look-saved"><div><span>09 / SAVE THE LOOK</span><h2>BUILD A SMALL<br/><em>REFERENCE SET.</em></h2><p>In a production account this can be persisted against the client profile. The frontend interaction is prepared for that workflow.</p></div><div className="saved-stack">{looks.slice(0,3).map((l,i)=><motion.figure key={l.id} style={{rotate:[-5,3,-1][i]}} whileHover={{y:-18,rotate:0}}><Image src={l.image} alt={l.title} fill/><figcaption>SAVE +</figcaption></motion.figure>)}</div></section>
<section className="look-note"><span>10 / BARBER NOTE</span><h2>“BRING THREE PHOTOS.<br/>ONE FOR SHAPE.<br/>ONE FOR TEXTURE.<br/><em>ONE YOU HATE.”</em></h2><p>MASON / CHAIR 02</p></section>
<section className="look-book"><div><span>11 / BOOK THE LOOK</span><h2>REFERENCE<br/><em> / APPOINTMENT</em></h2></div><div className="book-look-ticket"><span>LOW TAPER / TEXTURE</span><b>SIGNATURE CUT</b><strong>45 MIN</strong><small>WITH JACK / OR FIRST AVAILABLE</small><button onClick={()=>{booking.setService(looks[0].service);booking.setBarber(looks[0].barber)}}>ADD TO BOOKING </button></div></section>
<section className="look-final"><span>12 / YOUR VERSION</span><h2><RevealText>BRING THE REFERENCE.</RevealText><br/><em><RevealText>LEAVE WITH YOUR VERSION.</RevealText></em></h2><Link href="/booking">BOOK THE CONVERSATION </Link></section>
<AnimatePresence>{selected&&<motion.div className="look-lightbox" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} onClick={()=>setActive(null)}><motion.div initial={{clipPath:'inset(8% 8% 8% 8%)'}} animate={{clipPath:'inset(0% 0% 0% 0%)'}} exit={{clipPath:'inset(8% 8% 8% 8%)'}} onClick={e=>e.stopPropagation()}><div className="lb-image"><Image src={selected.image} alt={selected.title} fill/></div><div className="lb-copy"><button onClick={()=>setActive(null)}>CLOSE </button><span>{selected.category}</span><h2>{selected.title}</h2><p>BY {selected.barber.name}<br/>{selected.service.name} / {selected.service.duration} MIN</p><Link href="/booking" onClick={()=>{booking.setBarber(selected.barber);booking.setService(selected.service)}}>BOOK THIS LOOK </Link></div></motion.div></motion.div>}</AnimatePresence>
</main>}
