"use client";
import {EditorialImage as Image} from "@/components/media/EditorialImage";import Link from "next/link";import {useMemo,useRef,useState} from "react";import {motion,useScroll,useTransform} from "framer-motion";import {media} from "@/data/media";import {barbers} from "@/data/site";import {RevealLines,RevealText} from "@/components/motion/RevealText";import {ScrollWords} from "@/components/motion/ScrollWords";import {usePublicData} from "@/components/providers/PublicDataProvider";import {useDesktopMotion} from "@/components/motion/useMotionMode";
export function MembershipExperience(){const desktop=useDesktopMotion();const {barbers,memberships}=usePublicData();const [weeks,setWeeks]=useState(3);const yearly=Math.round(52/weeks);const saved=Math.max(0,yearly*4);const ref=useRef<HTMLElement>(null);const{scrollYProgress}=useScroll({target:ref,offset:['start end','end start']});const x=useTransform(scrollYProgress,[0,1],['0%','-24%']);const plan=useMemo(()=>weeks<=2?'FREQUENT':weeks<=4?'RHYTHM':'SEASONAL',[weeks]);return <main className="membership-v2">
<section className="mem-hero"><div><span>01 / MEMBERSHIP</span><h1><RevealLines lines={['ONE LESS','THING TO']}/><em><RevealLines lines={['THINK ABOUT.']}/></em></h1><p>Membership is not a discount card. It is a repeatable rhythm: your barber, your interval and priority access to the appointments you already know you need.</p></div><div className="mem-hero-circle"><span>YOUR<br/>RHYTHM</span><b>03</b><small>WEEKS</small></div></section>
<section className="mem-manifesto"><span>02 / THE IDEA</span><ScrollWords text="The best haircut is the one you stop managing. You know when it gets too long. You know the time you prefer. Your barber already knows the shape. Membership removes the repeated admin between those facts."/></section>
<section ref={ref} className="growth-rhythm"><div className="growth-pin"><div><span>03 / HAIR GROWTH RHYTHM</span><h2>WATCH THE<br/><em>SHAPE CHANGE.</em></h2></div><motion.div className="growth-track" style={desktop?{x}:undefined}>{[0,1,2,3,4,5].map((n)=><article key={n}><div className="growth-image"><Image src={media.looks[n%media.looks.length]} alt={`Hair growth week ${n+1}`} fill/></div><span>WEEK {String(n+1).padStart(2,'0')}</span><b>{['FRESH','SETTLED','LIVED-IN','REFRESH','GROWN','RESET'][n]}</b><p>{['Edges are clean. Shape is sharp.','The cut relaxes into its natural movement.','Still intentional, less styled.','Ideal point for a maintenance visit.','Weight begins to change the silhouette.','Time to rebuild the shape.'][n]}</p></article>)}</motion.div></div></section>
<section className="mem-calculator"><div><span>04 / FIND YOUR FREQUENCY</span><h2>HOW OFTEN DO<br/><em>YOU NOTICE IT?</em></h2><p>Move the interval to match when your current cut starts feeling wrong, not when the calendar says you should go.</p></div><div className="calculator-control"><output>{weeks}<small>WEEKS</small></output><input type="range" min="2" max="8" value={weeks} onChange={e=>setWeeks(Number(e.target.value))}/><div><span>2</span><span>4</span><span>6</span><span>8</span></div></div><motion.aside layout><small>YOUR RHYTHM</small><b>{plan}</b><p>ABOUT {yearly} VISITS / YEAR</p><span>EST. £{saved} VALUE IN PRIORITY + MEMBER RATE</span></motion.aside></section>
<section className="plan-bands"><span>05 / THE BANDS</span>{(memberships.length?memberships.map((m:any)=>[m.name,`EVERY ${Math.max(1,Math.round((m.frequencyDays||21)/7))} WEEKS`,`£${m.price} / ${(m.privileges||[]).slice(0,2).join(' + ')}`]):[['FREQUENT','EVERY 2–3 WEEKS','FOR SHORTER SHAPES + FADES'],['RHYTHM','EVERY 3–4 WEEKS','THE MOST COMMON RESET'],['SEASONAL','EVERY 5–8 WEEKS','LONGER HAIR + SCISSOR WORK']]).map((p:any,i:number)=><motion.article key={p[0]} whileHover={{x:i%2?18:-18}}><span>0{i+1}</span><b>{p[0]}</b><strong>{p[1]}</strong><small>{p[2]}</small><i></i></motion.article>)}</section>
<section className="member-privileges"><div><span>06 / WHAT CHANGES</span><h2>NOT MORE STUFF.<br/><em>LESS FRICTION.</em></h2></div><div>{[['01','PRIORITY WINDOWS','See selected time windows before general release.'],['02','BARBER CONTINUITY','Keep the same chair in the loop by default.'],['03','REBOOK IN ONE MOVE','Repeat service, barber and preferred time from your account.'],['04','MEMBER RATE','A small rate advantage for predictable recurring business.']].map(([n,t,c])=><article key={n}><span>{n}</span><b>{t}</b><p>{c}</p></article>)}</div></section>
<section className="priority-booking"><div className="priority-calendar"><span>07 / PRIORITY</span>{Array.from({length:21},(_,i)=><i className={[2,6,9,13,18].includes(i)?'open':''} key={i}>{i+1}</i>)}</div><div><h2>THE TIMES<br/>YOU ACTUALLY<br/><em>USE.</em></h2><p>Member inventory can be held for high-demand late afternoon and Saturday windows.</p></div></section>
<section className="barber-continuity"><div><span>08 / CONTINUITY</span><h2>THE SECOND VISIT<br/><em>STARTS FURTHER AHEAD.</em></h2><p>Your barber has the previous shape in mind. The consultation gets shorter because the context gets longer.</p></div><div className="continuity-stack">{barbers.slice(0,3).map((b,i)=><motion.figure key={b._id} style={{zIndex:3-i}} whileHover={{x:20*i,y:-10*i}}><Image src={b.portrait||media.portraits[i]} alt={b.name} fill/><figcaption>{b.name}<small>CHAIR {b.chairNumber}</small></figcaption></motion.figure>)}</div></section>
<section className="savings-visual"><span>09 / VALUE, SHOWN CLEARLY</span><h2>NO MYSTERY<br/><em>MATH.</em></h2><div className="savings-row"><span>STANDARD YEAR</span><i/><b>£{yearly*32}</b></div><div className="savings-row member"><span>MEMBER YEAR</span><i/><b>£{Math.max(0,yearly*32-saved)}</b></div><p>Example only, based on your selected {weeks}-week rhythm and a Signature Cut. Final membership pricing is managed in the admin panel.</p></section>
<section className="member-story"><div className="member-story-image"><Image src={media.chair} alt="Member in chair" fill/></div><div><span>10 / MEMBER 021</span><h2>“I BOOK THE<br/>SAME SLOT BEFORE<br/><em>I LEAVE.”</em></h2><p>ADAM / 3-WEEK RHYTHM / CHAIR 02</p></div></section>
<section className="mem-faq"><span>11 / QUESTIONS</span>{[['CAN I CHANGE BARBER?','Yes. Membership creates continuity, not lock-in.'],['WHAT IF I SKIP A VISIT?','Your schedule can be adjusted. The point is rhythm, not punishment.'],['IS THERE A CONTRACT?','The exact commercial terms are controlled in admin settings and should be shown clearly before checkout.'],['CAN I PAUSE?','Yes — useful for travel, longer growth phases or changing styles.']].map(([q,a])=><details key={q}><summary>{q}<span>+</span></summary><p>{a}</p></details>)}</section>
<section className="mem-final"><span>12 / JOIN THE RHYTHM</span><h2><RevealText>SET IT ONCE.</RevealText><br/><em><RevealText>KEEP IT SHARP.</RevealText></em></h2><Link href="/account">START MEMBERSHIP </Link></section>
</main>}
