"use client";
import {EditorialImage as Image} from "@/components/media/EditorialImage";import Link from "next/link";import {useRef,useState} from "react";import {motion,useScroll,useTransform} from "framer-motion";import {media} from "@/data/media";import {RevealLines,RevealText} from "@/components/motion/RevealText";import {useDesktopMotion} from "@/components/motion/useMotionMode";
export function VisitExperience(){const desktop=useDesktopMotion();const [door,setDoor]=useState(0);const [copied,setCopied]=useState(false);async function copyAddress(){try{await navigator.clipboard.writeText('14 King Street, Manchester M2');setCopied(true);window.setTimeout(()=>setCopied(false),1800)}catch{setCopied(false)}}const ref=useRef<HTMLElement>(null);const{scrollYProgress}=useScroll({target:ref,offset:['start start','end end']});const zoom=useTransform(scrollYProgress,[0,1],[1,1.35]);return <main className="visit-v2">
<section className="visit-hero"><Image src={media.exterior} alt="The Chair exterior" fill priority/><div/><span>01 / VISIT</span><h1><RevealLines lines={['FIND']}/><em><RevealLines lines={['THE DOOR.']}/></em></h1><p>14 KING STREET<br/>MANCHESTER / M2</p><aside><span>HOUSE STATUS</span><b>OPEN</b><small>UNTIL 20:00</small></aside></section>
<section className="visit-status"><span>02 / RIGHT NOW</span><div><b>OPEN</b><p>MONDAY–FRIDAY<br/>09:00–20:00</p></div><div><b>SAT</b><p>09:00–18:00</p></div><div><b>SUN</b><p>CLOSED</p></div><Link href="/booking">NEXT CHAIR / 17:30 </Link></section>
<section className="visit-address"><span>03 / ADDRESS</span><h2>14 KING<br/><em>STREET.</em></h2><p>MANCHESTER<br/>M2</p><button type="button" onClick={copyAddress}>{copied?'ADDRESS COPIED':'COPY ADDRESS'}</button></section>
<section className="visit-map"><div className="map-grid"><i/><i/><i/><i/><i/><i/><span className="map-river">IRWELL</span><span className="map-road r1">KING ST</span><span className="map-road r2">DEANSGATE</span><motion.div className="map-pin" animate={{scale:[1,1.18,1]}} transition={{repeat:Infinity,duration:2}}>THE CHAIR</motion.div></div><div><span>04 / THE AREA</span><h2>YOU'RE<br/><em>CLOSE.</em></h2><p>Central enough to arrive without planning the whole day around it. Quiet enough once the door closes.</p></div></section>
<section ref={ref} className="find-door"><div className="find-door-pin"><motion.div className="find-door-image" style={desktop?{scale:zoom}:undefined}><Image src={[media.street,media.exterior,media.house][door]} alt="Find the door sequence" fill/></motion.div><div className="door-ui"><span>05 / FIND THE DOOR</span><h2>{['STREET','BUILDING','ENTRANCE'][door]}</h2><div>{['STREET','BUILDING','ENTRANCE'].map((x,i)=><button key={x} className={door===i?'active':''} onClick={()=>setDoor(i)}><span>0{i+1}</span>{x}</button>)}</div><p>{['Walk King Street until you see the dark frontage between the lighter stone facades.','Look for the restrained THE CHAIR wordmark rather than a bright shop sign.','The entrance is the narrow dark door on the left of the main glazing.'][door]}</p></div></div></section>
<section className="visit-walk"><div><span>06 / WALKING</span><h2>FROM<br/><em>DEANSGATE.</em></h2><strong>06 MIN</strong></div><ol><li><span>01</span>EXIT TOWARD KING STREET</li><li><span>02</span>WALK EAST / TWO BLOCKS</li><li><span>03</span>PASS THE STONE CORNER</li><li><span>04</span>THE DARK FRONTAGE IS YOURS</li></ol></section>
<section className="visit-driving"><div className="drive-image"><Image src={media.street} alt="Driving to The Chair" fill/></div><div><span>07 / DRIVING</span><h2>DON'T CIRCLE<br/><em>THE BLOCK.</em></h2><p>Use the nearby public car park, then finish the last two minutes on foot. The street itself is better for drop-off than waiting.</p><a className="visit-directions" href="https://www.google.com/maps/search/?api=1&query=14+King+Street+Manchester+M2" target="_blank" rel="noreferrer">OPEN DIRECTIONS</a></div></section>
<section className="visit-transit"><span>08 / TRANSIT</span>{[['TRAM','ST PETER’S SQUARE','07 MIN WALK'],['TRAIN','MANCHESTER VICTORIA','12 MIN WALK'],['BUS','KING ST / CROSS ST','02 MIN WALK']].map(([t,p,d],i)=><article key={t}><span>0{i+1}</span><b>{t}</b><strong>{p}</strong><small>{d}</small></article>)}</section>
<section className="visit-parking"><div><span>09 / PARKING</span><h2>LEAVE THE CAR.<br/><em>KEEP THE TIME.</em></h2></div><div className="parking-ticket"><span>NEAREST PUBLIC PARKING</span><b>05 MIN WALK</b><small>ALLOW 10 MINUTES BEFORE YOUR APPOINTMENT</small><i>P</i></div></section>
<section className="visit-access"><span>10 / ACCESSIBILITY</span><h2>BEFORE YOU<br/><em>ARRIVE.</em></h2><div><p>Step-free route information</p><b>AVAILABLE</b></div><div><p>Assistance / appointment notes</p><b>ADD DURING BOOKING</b></div><div><p>Need something specific?</p><b>CALL THE HOUSE</b></div></section>
<section className="visit-contact"><div><span>11 / CONTACT</span><h2>NEED THE<br/><em>HUMAN VERSION?</em></h2></div><div><a href="tel:+441610000000">+44 (0)161 000 0000 </a><a href="mailto:hello@thechair.house">HELLO@THECHAIR.HOUSE </a><span>@THECHAIR.HOUSE</span></div></section>
<section className="visit-final"><span>12 / ARRIVE WITH A CHAIR WAITING</span><h2><RevealText>YOU FOUND THE DOOR.</RevealText><br/><em><RevealText>NOW TAKE THE CHAIR.</RevealText></em></h2><Link href="/booking">BOOK YOUR VISIT </Link></section>
</main>}
