import express from "express"; import { z } from "zod"; import { asyncHandler,slugify } from "./utils.js"; import { requireAdmin,requireAuth,sign,hash,verify } from "./auth.js"; import { Appointment,Barber,Client,Journal,Lookbook,Membership,Review,Service,Settings,SiteContent,User } from "./models.js"; import { cancelAppointment,createAppointment,getAvailability,rescheduleAppointment } from "./booking.js";
export const router=express.Router();
router.get("/health",(req,res)=>res.json({ok:true,service:"the-chair-api"}));
router.post("/auth/register",asyncHandler(async(req,res)=>{const schema=z.object({name:z.string().min(2),email:z.string().email(),password:z.string().min(8),phone:z.string().optional()});const d=schema.parse(req.body);if(await User.findOne({email:d.email}))return res.status(409).json({message:"Email already registered"});const u=await User.create({name:d.name,email:d.email,passwordHash:await hash(d.password),role:"client"});const c=await Client.create({user:u._id,name:d.name,email:d.email,phone:d.phone,onboarded:true});res.status(201).json({token:sign(u),user:{id:u._id,name:u.name,email:u.email,role:u.role},client:c})}));
router.post("/auth/login",asyncHandler(async(req,res)=>{const d=z.object({email:z.string().email(),password:z.string()}).parse(req.body);const u=await User.findOne({email:d.email.toLowerCase()});if(!u||!await verify(d.password,u.passwordHash))return res.status(401).json({message:"Invalid credentials"});const c=await Client.findOne({user:u._id});res.json({token:sign(u),user:{id:u._id,name:u.name,email:u.email,role:u.role},client:c})}));
router.get("/auth/me",requireAuth,asyncHandler(async(req,res)=>{const c=await Client.findOne({user:req.user._id}).populate("preferredBarber");res.json({user:{id:req.user._id,name:req.user.name,email:req.user.email,role:req.user.role},client:c})}));
router.get("/public/bootstrap",asyncHandler(async(req,res)=>{const [services,barbers,reviews,settings,journal,lookbook,memberships,content]=await Promise.all([Service.find({active:true}).sort("sort"),Barber.find({active:true}),Review.find({status:"approved"}).sort("-createdAt").limit(12),Settings.findOne({key:"global"}),Journal.find({status:"published"}).sort("-publishedAt").limit(12),Lookbook.find({active:true}).sort("sort").limit(30).populate("barber service"),Membership.find({active:true}),SiteContent.find({active:true})]);res.json({services,barbers,reviews,settings,journal,lookbook,memberships,content})}));
router.get("/availability",asyncHandler(async(req,res)=>{const q=z.object({barberId:z.string(),serviceId:z.string(),date:z.string().regex(/^\d{4}-\d{2}-\d{2}$/)}).parse(req.query);res.json({slots:await getAvailability(q)})}));
router.get("/public/next-chairs",asyncHandler(async(req,res)=>{const [barbers,services]=await Promise.all([Barber.find({active:true}).sort("chairNumber"),Service.find({active:true}).sort("sort")]);const found=[];for(const barber of barbers){const service=services.find(s=>!barber.serviceIds?.length||barber.serviceIds.some(id=>String(id)===String(s._id)));if(!service)continue;let hit=null;for(let i=0;i<7&&!hit;i++){const d=new Date();d.setDate(d.getDate()+i);const date=d.toISOString().slice(0,10);const slots=await getAvailability({barberId:String(barber._id),serviceId:String(service._id),date});if(slots.length)hit={date,time:slots[0]}}if(hit)found.push({barber,service,...hit});if(found.length>=4)break}res.json({items:found})}));
router.post("/appointments",asyncHandler(async(req,res)=>{const clientSchema=z.object({name:z.string().min(2),email:z.string().email().optional().or(z.literal("")),phone:z.string().min(5).optional().or(z.literal("")),notes:z.string().optional()}).refine(data=>Boolean(data.email?.trim()||data.phone?.trim()),{message:"Please provide at least a phone number or email address"});const d=z.object({serviceId:z.string(),barberId:z.string(),date:z.string(),time:z.string(),client:clientSchema}).parse(req.body);const a=await createAppointment({serviceId:d.serviceId,barberId:d.barberId,date:d.date,time:d.time,clientData:d.client});res.status(201).json({appointment:await a.populate(["service","barber","client"])})}));
router.get("/appointments/:id",asyncHandler(async(req,res)=>{const a=await Appointment.findById(req.params.id).populate("service barber client");if(!a)return res.status(404).json({message:"Appointment not found"});res.json({appointment:a})}));
router.post("/appointments/:id/request-change",requireAuth,asyncHandler(async(req,res)=>{const d=z.object({newDate:z.string().regex(/^\d{4}-\d{2}-\d{2}$/),newTime:z.string(),notes:z.string().optional()}).parse(req.body);const client=await Client.findOne({user:req.user._id});if(!client)return res.status(404).json({message:"Client profile not found"});const appt=await Appointment.findOne({_id:req.params.id,client:client._id});if(!appt)return res.status(404).json({message:"Appointment not found"});appt.changeRequest={newDate:d.newDate,newTime:d.newTime,notes:d.notes||"",requestedAt:new Date(),status:"pending"};appt.status="change_requested";await appt.save();res.json({appointment:await appt.populate("service barber client")})}));
router.post("/reviews",asyncHandler(async(req,res)=>{const d=z.object({name:z.string(),email:z.string().email().optional(),quote:z.string().min(8),rating:z.number().min(1).max(5),service:z.string().optional(),appointment:z.string().optional()}).parse(req.body);res.status(201).json(await Review.create(d))}));
router.get("/clients/me",requireAuth,asyncHandler(async(req,res)=>{const client=await Client.findOne({user:req.user._id}).populate("preferredBarber");if(!client)return res.status(404).json({message:"Client profile not found"});const now=new Date();const [upcoming,history]=await Promise.all([Appointment.find({client:client._id,startAt:{$gte:now},status:{$in:["confirmed","change_requested","pending"]}}).sort("startAt").populate("service barber"),Appointment.find({client:client._id,$or:[{startAt:{$lt:now}},{status:{$in:["completed","cancelled","no-show"]}}]}).sort("-startAt").limit(20).populate("service barber")]);res.json({client,next:upcoming[0]||null,upcoming,history})}));
router.put("/clients/me",requireAuth,asyncHandler(async(req,res)=>{const {name,phone,preferences,preferredBarber}=req.body;const allowed={name,phone,preferences,preferredBarber};Object.keys(allowed).forEach(k=>allowed[k]===undefined&&delete allowed[k]);res.json(await Client.findOneAndUpdate({user:req.user._id},{$set:allowed},{new:true}).populate("preferredBarber"))}));

router.use("/admin",requireAuth,requireAdmin);
router.get("/admin/dashboard",asyncHandler(async(req,res)=>{const now=new Date(),start=new Date(now);start.setHours(0,0,0,0);const tomorrow=new Date(start.getTime()+86400000),week=new Date(start.getTime()+7*86400000);const [todayAppointments,weekAppointments,clients,pendingReviews,upcoming]=await Promise.all([Appointment.countDocuments({startAt:{$gte:start,$lt:tomorrow},status:{$ne:"cancelled"}}),Appointment.countDocuments({startAt:{$gte:start,$lt:week},status:{$ne:"cancelled"}}),Client.countDocuments(),Review.countDocuments({status:"pending"}),Appointment.find({startAt:{$gte:now},status:{$in:["confirmed","change_requested"]}}).sort("startAt").limit(10).populate("client service barber")]);res.json({todayAppointments,weekAppointments,clients,pendingReviews,upcoming})}));

function crud(path,Model,{beforeSave,listQuery={}}={}){router.get(`/admin/${path}`,asyncHandler(async(req,res)=>res.json({items:await Model.find(listQuery).sort("-updatedAt").limit(200)})));router.post(`/admin/${path}`,asyncHandler(async(req,res)=>{const data=beforeSave?beforeSave({...req.body}):req.body;res.status(201).json(await Model.create(data))}));router.put(`/admin/${path}/:id`,asyncHandler(async(req,res)=>{const data=beforeSave?beforeSave({...req.body}):req.body;const x=await Model.findByIdAndUpdate(req.params.id,{$set:data},{new:true,runValidators:true});if(!x)return res.status(404).json({message:"Not found"});res.json(x)}));router.delete(`/admin/${path}/:id`,asyncHandler(async(req,res)=>{const x=await Model.findByIdAndDelete(req.params.id);if(!x)return res.status(404).json({message:"Not found"});res.json({ok:true})}))}
crud("services",Service,{beforeSave:d=>({...d,slug:d.slug||slugify(d.name)})});crud("barbers",Barber,{beforeSave:d=>({...d,slug:d.slug||slugify(d.name),specialties:Array.isArray(d.specialties)?d.specialties:String(d.specialties||"").split(",").map(x=>x.trim()).filter(Boolean)})});crud("clients",Client);crud("reviews",Review);crud("journal",Journal,{beforeSave:d=>({...d,slug:d.slug||slugify(d.title),publishedAt:d.status==="published"?(d.publishedAt||new Date()):d.publishedAt})});crud("lookbook",Lookbook);crud("memberships",Membership,{beforeSave:d=>({...d,slug:d.slug||slugify(d.name)})});crud("content",SiteContent);
router.get("/admin/appointments",asyncHandler(async(req,res)=>res.json({items:await Appointment.find().sort("-startAt").limit(250).populate("client service barber")})));
router.post("/admin/appointments",asyncHandler(async(req,res)=>{const d=req.body;const clientData=d.client||{name:d.clientName||"Walk-in",email:d.email||`walkin-${Date.now()}@local.invalid`,phone:d.phone||"N/A",notes:d.notes};const a=await createAppointment({serviceId:d.serviceId,barberId:d.barberId,date:d.date,time:d.time,clientData,source:"admin"});res.status(201).json(await a.populate(["client","service","barber"]))}));
router.post("/admin/appointments/:id/approve-change",asyncHandler(async(req,res)=>{const a=await Appointment.findById(req.params.id);if(!a||!a.changeRequest?.newDate||!a.changeRequest?.newTime)return res.status(400).json({message:"No pending change request"});const updated=await rescheduleAppointment(req.params.id,{serviceId:String(a.service),barberId:String(a.barber),date:a.changeRequest.newDate,time:a.changeRequest.newTime});updated.changeRequest.status="approved";updated.status="confirmed";await updated.save();res.json({appointment:await updated.populate("client service barber")})}));
router.post("/admin/appointments/:id/reject-change",asyncHandler(async(req,res)=>{const a=await Appointment.findById(req.params.id);if(!a)return res.status(404).json({message:"Appointment not found"});a.changeRequest.status="rejected";a.status="confirmed";await a.save();res.json({appointment:await a.populate("client service barber")})}));
router.put("/admin/appointments/:id",asyncHandler(async(req,res)=>{if(req.body.status==="cancelled")return res.json(await cancelAppointment(req.params.id));let a;if(req.body.date&&req.body.time)a=await rescheduleAppointment(req.params.id,{serviceId:req.body.serviceId,barberId:req.body.barberId,date:req.body.date,time:req.body.time});else{const allowed={status:req.body.status,notes:req.body.notes};Object.keys(allowed).forEach(k=>allowed[k]===undefined&&delete allowed[k]);a=await Appointment.findByIdAndUpdate(req.params.id,{$set:allowed},{new:true})}res.json(await a.populate("client service barber"))}));
router.delete("/admin/appointments/:id",asyncHandler(async(req,res)=>{await cancelAppointment(req.params.id);res.json({ok:true})}));
router.get("/admin/settings",asyncHandler(async(req,res)=>{let s=await Settings.findOne({key:"global"});if(!s)s=await Settings.create({key:"global"});res.json({items:[s]})}));
router.post("/admin/settings",asyncHandler(async(req,res)=>res.json(await Settings.findOneAndUpdate({key:"global"},{$set:req.body},{new:true,upsert:true}))));
router.put("/admin/settings/:id",asyncHandler(async(req,res)=>res.json(await Settings.findOneAndUpdate({key:"global"},{$set:req.body},{new:true,upsert:true}))));
router.delete("/admin/settings/:id",(req,res)=>res.status(405).json({message:"Global settings cannot be deleted"}));
