import { connectDB } from "./db.js";import { User,Client,Service,Barber,Review,Journal,Lookbook,Membership,Settings,Appointment,AppointmentLock,SiteContent } from "./models.js";import { hash } from "./auth.js";
await connectDB();await Promise.all([User.deleteMany({}),Client.deleteMany({}),Service.deleteMany({}),Barber.deleteMany({}),Review.deleteMany({}),Journal.deleteMany({}),Lookbook.deleteMany({}),Membership.deleteMany({}),Settings.deleteMany({}),Appointment.deleteMany({}),AppointmentLock.deleteMany({}),SiteContent.deleteMany({})]);
const services=await Service.insertMany([
{slug:"signature-cut",name:"SIGNATURE CUT",description:"Consult, cut, detail and finish — one chair, no rush.",duration:45,price:32,category:"hair",active:true,sort:1,image:"https://images.unsplash.com/photo-1622296089863-eb7fc530daa8?auto=format&fit=crop&w=1200&q=85"},
{slug:"cut-beard",name:"CUT + BEARD",description:"A complete reset with shape, balance and finish.",duration:60,price:44,category:"both",active:true,sort:2,image:"https://images.unsplash.com/photo-1599351431202-1e0f0137899a?auto=format&fit=crop&w=1200&q=85"},
{slug:"beard-detail",name:"BEARD DETAIL",description:"Shape, line, soften and finish.",duration:30,price:24,category:"beard",active:true,sort:3,image:"https://images.unsplash.com/photo-1622287162716-f311baa1a2b8?auto=format&fit=crop&w=1200&q=85"},
{slug:"full-restyle",name:"FULL RESTYLE",description:"More time for a bigger change and a proper plan.",duration:70,price:49,category:"hair",active:true,sort:4,image:"https://images.unsplash.com/photo-1621605815971-fbc98d665033?auto=format&fit=crop&w=1200&q=85"},
{slug:"long-scissor-work",name:"LONG / SCISSOR WORK",description:"Movement, weight and shape for medium-to-long hair.",duration:55,price:39,category:"hair",active:true,sort:5,image:"https://images.unsplash.com/photo-1621607512022-6aecc4fed814?auto=format&fit=crop&w=1200&q=85"}
]);
const common={mon:{start:"09:00",end:"20:00",enabled:true},tue:{start:"09:00",end:"20:00",enabled:true},wed:{start:"09:00",end:"20:00",enabled:true},thu:{start:"09:00",end:"20:00",enabled:true},fri:{start:"09:00",end:"20:00",enabled:true},sat:{start:"09:00",end:"18:00",enabled:true},sun:{start:"10:00",end:"16:00",enabled:false}};
const portraits=["https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=1000&q=85","https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=1000&q=85","https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=1000&q=85","https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=1000&q=85"];
await Barber.insertMany([["jack","JACK HARPER","01",["FADE","TEXTURE","BEARD"]],["mason","MASON REED","02",["SCISSOR","CLASSIC","RESTYLE"]],["elliot","ELLIOT COLE","03",["SHORT HAIR","BEARD","DETAIL"]],["noah","NOAH VALE","04",["LONG HAIR","TEXTURE","SCISSOR"]]].map((x,i)=>({slug:x[0],name:x[1],chairNumber:x[2],specialties:x[3],bio:"Quiet precision, deliberate consultation and a finish that still works tomorrow.",portrait:portraits[i],active:true,serviceIds:services.map(s=>s._id),workingHours:common})));
await Review.insertMany([{name:"James",quote:"The first barber who actually listened.",rating:5,service:"Cut + Beard",status:"approved"},{name:"Daniel",quote:"It feels less like an appointment and more like protected time.",rating:5,service:"Signature Cut",status:"approved"},{name:"Owen",quote:"I stopped explaining the same haircut every three weeks.",rating:5,service:"Membership",status:"pending"}]);
await Journal.insertMany([{title:"The 3-Week Rule",slug:"the-3-week-rule",excerpt:"When a cut starts losing intention.",body:"A practical guide to recognizing the point where shape starts to slip.",type:"feature",status:"published",publishedAt:new Date()},{title:"How to Ask for What You Actually Want",slug:"how-to-ask",excerpt:"Translate references into useful barber language.",body:"Use reference photos as a starting point, then explain the texture and maintenance you like.",type:"guide",status:"published",publishedAt:new Date()}]);
await Lookbook.insertMany(services.map((s,i)=>({title:s.name,category:s.category,image:s.image,service:s._id,description:s.description,active:true,sort:i+1})));
await Membership.insertMany([{name:"THE RHYTHM / 21",slug:"rhythm-21",description:"A fresh chair every three weeks.",price:42,frequencyDays:21,privileges:["Priority windows","Preferred barber continuity","Easy rebook"]},{name:"THE RHYTHM / 14",slug:"rhythm-14",description:"Built for clients who want the shape constantly fresh.",price:58,frequencyDays:14,privileges:["Priority windows","Preferred barber continuity","Easy rebook"]}]);
await SiteContent.insertMany([{key:"home.hero",page:"home",eyebrow:"01 / ARRIVAL",title:"TAKE YOUR CHAIR.",copy:"A private grooming experience, built around your time.",active:true},{key:"home.manifesto",page:"home",eyebrow:"03 / MANIFESTO",title:"NOT JUST A HAIRCUT.",copy:"45 minutes. Reserved for you.",active:true},{key:"home.final",page:"home",eyebrow:"17 / NEXT CHAIR",title:"YOUR CHAIR IS WAITING.",copy:"Take the next opening or build your own appointment.",active:true}]);
await Settings.create({key:"global",shopName:"THE CHAIR",phone:"+44 161 555 0144",email:"hello@thechair.example",address:"14 King Street, Manchester M2",openingCopy:"MON–SAT / 09:00–20:00",bookingInterval:15,depositEnabled:false,depositAmount:10,timezone:"Europe/London"});
await User.create({name:"The Chair Admin",email:"admin@thechair.local",passwordHash:await hash("ChangeMe123!"),role:"admin",active:true});console.log("Seed complete. Admin: admin@thechair.local / ChangeMe123!");process.exit(0);
