"use client";
import {useEffect,useState} from "react";import {Clock3,Plus,RefreshCw,Trash2,X} from "lucide-react";import {api} from "@/lib/api";import {toast} from "sonner";import type {Service} from "@/lib/types";
const days=[['mon','MON'],['tue','TUE'],['wed','WED'],['thu','THU'],['fri','FRI'],['sat','SAT'],['sun','SUN']] as const;
const defaults:any={mon:{start:'09:00',end:'20:00',enabled:true},tue:{start:'09:00',end:'20:00',enabled:true},wed:{start:'09:00',end:'20:00',enabled:true},thu:{start:'09:00',end:'20:00',enabled:true},fri:{start:'09:00',end:'20:00',enabled:true},sat:{start:'09:00',end:'18:00',enabled:true},sun:{start:'10:00',end:'16:00',enabled:false}};
export function BarberManager(){const[rows,setRows]=useState<any[]>([]);const[services,setServices]=useState<Service[]>([]);const[edit,setEdit]=useState<any>(null);const[open,setOpen]=useState(false);const[loading,setLoading]=useState(true);const[schedule,setSchedule]=useState<any>(defaults);const[selectedServices,setSelectedServices]=useState<string[]>([]);
async function load(){setLoading(true);try{const[a,b]=await Promise.all([api<any>('/admin/barbers'),api<any>('/public/bootstrap')]);setRows(a.items||[]);setServices(b.services||[])}catch(e:any){toast.error(e.message)}finally{setLoading(false)}}useEffect(()=>{load()},[]);
function start(x:any=null){setEdit(x);setSchedule(x?.workingHours||structuredClone(defaults));setSelectedServices((x?.serviceIds||[]).map((v:any)=>String(v?._id||v)));setOpen(true)}
async function save(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const fd=new FormData(e.currentTarget);const body={name:fd.get('name'),slug:fd.get('slug'),chairNumber:fd.get('chairNumber'),bio:fd.get('bio'),specialties:String(fd.get('specialties')||'').split(',').map(x=>x.trim()).filter(Boolean),portrait:fd.get('portrait'),active:fd.get('active')==='on',workingHours:schedule,serviceIds:selectedServices};try{await api(edit?`/admin/barbers/${edit._id}`:'/admin/barbers',{method:edit?'PUT':'POST',body:JSON.stringify(body)});toast.success('Barber + schedule saved');setOpen(false);load()}catch(e:any){toast.error(e.message)}}
async function remove(id:string){if(!confirm('Delete this barber? Existing appointment history should normally be preserved by deactivating instead.'))return;try{await api(`/admin/barbers/${id}`,{method:'DELETE'});load()}catch(e:any){toast.error(e.message)}}
return <div className="resource barber-control"><header><div><span>CONTROL ROOM / PEOPLE + SCHEDULES</span><h1>Barbers</h1><p>Manage chair identity, specialties, service compatibility and working hours from one screen.</p></div><div><button onClick={load}><RefreshCw size={16}/></button><button className="admin-primary" onClick={()=>start()}><Plus size={16}/>NEW BARBER</button></div></header>{loading?<div className="admin-skeleton"><i/><i/><i/></div>:<div className="barber-admin-grid">{rows.map((x:any)=><article key={x._id}><div className="barber-admin-photo" style={{backgroundImage:`url(${x.portrait||''})`}}/><span>CHAIR {x.chairNumber} / {x.active?'ACTIVE':'OFF'}</span><h2>{x.name}</h2><p>{x.specialties?.join(' / ')}</p><div><Clock3 size={14}/><b>{Object.values(x.workingHours||{}).filter((d:any)=>d.enabled).length} WORKING DAYS</b></div><footer><button onClick={()=>start(x)}>EDIT SCHEDULE </button><button onClick={()=>remove(x._id)}><Trash2 size={14}/></button></footer></article>)}</div>}{open&&<div className="admin-modal barber-modal"><form onSubmit={save}><div className="modal-head"><div><span>{edit?'EDIT BARBER':'NEW BARBER'}</span><h2>CHAIR PROFILE + SCHEDULE</h2></div><button type="button" onClick={()=>setOpen(false)}><X size={18}/></button></div><label>NAME<input name="name" defaultValue={edit?.name||''} required/></label><label>SLUG<input name="slug" defaultValue={edit?.slug||''}/></label><label>CHAIR NUMBER<input name="chairNumber" defaultValue={edit?.chairNumber||''} required/></label><label>PORTRAIT URL<input name="portrait" defaultValue={edit?.portrait||''}/></label><label className="wide">BIO<textarea name="bio" defaultValue={edit?.bio||''}/></label><label className="wide">SPECIALTIES / COMMA SEPARATED<input name="specialties" defaultValue={edit?.specialties?.join(', ')||''}/></label><label className="toggle-line">ACTIVE<input type="checkbox" name="active" defaultChecked={edit?.active??true}/></label><div className="schedule-editor"><span>WEEKLY HOURS</span>{days.map(([key,label])=>{const d=schedule[key]||defaults[key];return <div key={key}><button type="button" className={d.enabled?'on':''} onClick={()=>setSchedule((s:any)=>({...s,[key]:{...d,enabled:!d.enabled}}))}>{label}</button><input type="time" value={d.start} disabled={!d.enabled} onChange={e=>setSchedule((s:any)=>({...s,[key]:{...d,start:e.target.value}}))}/><span> / </span><input type="time" value={d.end} disabled={!d.enabled} onChange={e=>setSchedule((s:any)=>({...s,[key]:{...d,end:e.target.value}}))}/></div>})}</div><div className="service-compat"><span>SERVICE COMPATIBILITY</span>{services.map(s=><label key={s._id}><input type="checkbox" checked={selectedServices.includes(s._id)} onChange={()=>setSelectedServices(v=>v.includes(s._id)?v.filter(x=>x!==s._id):[...v,s._id])}/><b>{s.name}</b><small>{s.duration} MIN</small></label>)}</div><button className="admin-primary" type="submit">SAVE BARBER + HOURS / </button></form></div>}</div>}
